### PR TITLE
Music Chords Diagrams: Fixes/improves triggering

### LINKED ISSUE #3841: Music Chords Diagrams:
The following two searches return the same results:
  
**c minor ukulele chord**   

**c major ukulele chord**

------
IA Page:  http://duck.co/ia/view/chord_diagrams 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @charles-I

### PR DESCRIPTION
**Pull request by nalinbhardwaj**
## Description of new Instant Answer, or changes

- Fixes regex to treat whitespace correctly. Currently, all searches showed the same chords for an instrument(!).
- Allows instruments to have multiple names matched via regex. For example, `ukulele` is very popular as `uke`. Now it triggers for both.
- Fixes handling of mods and makes processing more efficient.
- Handles plurals(`tabs`, `chords`) in queries.

## Related Issues and Discussions

Fixes #3841, #3386.

## People to notify

@ezgraphs @charles-l @mintsoft @edgesince84 

## Testing & Review
To be completed by Community Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [ ] Title follows correct format (Specifies Instant Answer + Purpose)
- [ ] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Instant Answer Page** (for new Instant Answers)
- [ ] Instant Answer page is correctly filled out and contains:
    - The **Title** is appropriately named and formatted
    - The **IA topics** are present and appropriate
    - The **Description** is clear and coherent
    - **Source Name** exists if applicable
    - All **Example Queries** trigger on [Beta](https://beta.duckduckgo.com/)

**Code**
- [ ] Adheres to the [DuckDuckGo Style Guide](https://docs.duckduckhack.com/resources/code-style-guide.html)
- [ ] Behaviour is appropriately tested. If improvement, tests are adequately extended.
- [ ] There is no unnecessary files in place (such as editor config files)
- [ ] There is no API keys / secrets present
- [ ] Tests are passing (run `$ duckpan test <fathead_id>`)
    - Tester should report any failures

**Ready to merge?**

- [ ] Has this IA been deployed to and tested on [beta.duckduckgo.com](https://beta.duckduckgo.com/)?
- [ ] For larger commits, has this been approved be more than one community member?
- [ ] The number of reviews is appropriate for this type of PR
- [ ] The commit message is clear, coherent and fitting

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/chord_diagrams

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by nalinbhardwaj** [comment]
I've made some more changes to the triggering mechanisms to allow for more than one name for an instrument. Details in description. Also, @pjhampton calling this `Priority: Low` might not be a very good idea. It's almost as if we're serving wrong information here. Still it's your call. :)

**Comment by pjhampton** [comment]
@nalinbhardwaj anything that is not in the High Impact tasks category is considered low priority. We (as a community) need to focus on what matters most.

File: lib/DDG/Goodie/ChordDiagrams.pm [hunk 1]
```diff
@@ -151,12 +153,12 @@ my %mod_hash = (sharp => 1, b => -1);
 sub items {
     my @words = split(" ", lc $_[0]);
     $_[0] = join("sharp", split("#", $_[0]));
-    my ($temp, $key, $mod, $chord, $dom, $temp2) = /( |^)([a-g])(sharp|b|)(m|min|minor|M|maj|major|sus[24]|aug9?|)(5|7|9|11|13|)( |$)/i ;
+    my ($temp, $key, $mod, $chord, $dom, $temp2) = /( |^)(?:\s)?([a-g])(?:\s)?(sharp|b|)(?:\s)?(m|min|minor|M|maj|major|sus[24]|aug9?|)(?:\s)?(5|7|9|11|13|)(?:\s)?( |$)/i;
```
Comment (charles-l) [inline lib/DDG/Goodie/ChordDiagrams.pm]: I agree that spaces should be allowed (but not matched). Maybe use `*` rather than `?` so it can match multiple spaces?

Comment (nalinbhardwaj) [inline lib/DDG/Goodie/ChordDiagrams.pm]: @charles-l done, thanks.

**Comment by mintsoft** [comment]
@nalinbhardwaj can we add some tests for the cases you know you've fixed the triggering on?

File: lib/DDG/Goodie/ChordDiagrams.pm [hunk 2]
```diff
@@ -151,12 +153,12 @@ my %mod_hash = (sharp => 1, b => -1);
 sub items {
     my @words = split(" ", lc $_[0]);
     $_[0] = join("sharp", split("#", $_[0]));
-    my ($temp, $key, $mod, $chord, $dom, $temp2) = /( |^)([a-g])(sharp|b|)(m|min|minor|M|maj|major|sus[24]|aug9?|)(5|7|9|11|13|)( |$)/i ;
+    my ($temp, $key, $mod, $chord, $dom, $temp2) = /( |^)(?:\s)*([a-g])(?:\s)*(sharp|b|)(?:\s)*(m|min|minor|M|maj|major|sus[24]|aug9?|)(?:\s)*(5|7|9|11|13|)(?:\s)*( |$)/i;
```
Comment (mintsoft) [inline lib/DDG/Goodie/ChordDiagrams.pm]: Definitely worth adding tests for the new patterns supported here

Comment (nalinbhardwaj) [inline lib/DDG/Goodie/ChordDiagrams.pm]: Not a lot of new patterns being supported, I've added relevant tests nonetheless. Thanks.

**Comment by nalinbhardwaj** [comment]
I've also added support for queries containing `tabs` and `chords` after your reviews @charles-l @mintsoft.

**Comment by moollaza** [comment]
Deploying to Beta 👍

**Comment by nalinbhardwaj** [comment]
Any reviews @mintsoft/@moollaza?

**Comment by mintsoft** [comment]
This looks good to me

**Comment by bsstoner** [comment]
This was released to production 🚀
